config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  root 'pages#index'
  get 'pages/help'

  resources :users

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  resources :topics

  get 'favorites/index'
  post '/favorites', to: 'favorites#create'
  delete '/favorites', to: 'favorites#destroy'

  get 'comments', to: 'comments#new'
  post '/comments', to: 'comments#create'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  validates :lines, presence: true, length: {maximum: 1000 }

  belongs_to :user
  belongs_to :topic
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :topic
end

app/models/topic.rb
class Topic < ApplicationRecord
  validates :user_id, presence: true
  validates :description, presence: true
  validates :image, presence: true

  belongs_to :user

  mount_uploader :image, ImageUploader

  has_many :favorites
  has_many :favorite_users, through: :favorites, source: 'user'
  has_many :comments
  has_many :comment_users, through: :favorites, source: 'user'
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  validates :name, presence: true, length: {maximum: 15}
  ML_REGEX = /[A-Za-z0-9._+]+@[A-Za-z]+.[A-Za-z]/
  validates :email, presence: true, format: { with: ML_REGEX }
  PW_REGEX = /\A(?=.*?[a-z])(?=.*?\d)[a-z\d]{8,32}\z/i
  validates :password, presence: true, format: { with: PW_REGEX }

  has_secure_password

  has_many :topics
  has_many :favorites
  has_many :favorite_topics, through: :favorites, source: 'topic'
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  add_flash_types :success, :info, :warning, :danger

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !current_user.nil?
  end

  helper_method :current_user, :logged_in?
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
    @comment = Comment.new
    @topic_id = params[:topic_id]
  end

  def index
    @comment = current_user.comment
  end

  def create
    comment = Comment.new
    comment.user_id = current_user.id
    comment.topic_id = params[:topic_id]
    comment.lines = lines_params[:lines]

    if comment.save
      redirect_to topics_path, success: 'コメントを登録しました'
    else
      redirect_to topics_path, danger: 'コメントの登録に失敗しました'
    end
  end

private
  #ストロングパラメータ実装
  def lines_params
    params.require(:comment).permit(:lines)
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def index
    @favorite_topics = current_user.favorite_topics
  end

  def create
    favorite = Favorite.new
    favorite.user_id = current_user.id
    favorite.topic_id = params[:topic_id]

    if favorite.save
      redirect_to topics_path, success: 'お気に入りに登録しました'
    else
      redirect_to topics_path, danger: 'お気に入りに登録に失敗しました'
    end
  end

  def destroy
    favorite = Favorite.find_by(user_id: current_user.id, topic_id: params[:topic_id])
    favorite.destroy if favorite.present?

    if favorite.destroyed?
      redirect_to topics_path, success: 'お気に入りを解除しました'
    else
      redirect_to topics_path, success: 'お気に入り解除に失敗しました'
    end
  end
end

app/controllers/favrites_controller.rb
class FavritesController < ApplicationController
end

app/controllers/pages_controler.rb
class PagesController < ApplicationController
  def index
  end

  def help
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
#require 'pry'#debug
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email])
#binding pry#debug
    if user && user.authenticate(params[:session][:password])
      log_in user
      redirect_to root_path, success: 'ログインに成功しました'
    else
      flash.now[:danger] = 'ログインに失敗しました'
      render :new
    end
  end

  def destroy
    log_out
    redirect_to root_url, info: 'ログアウトしました'
  end

  private
    def email_params
      (params.require(:session).permit(:email))[:email]
    end

    def password_params
      (params.require(:session).permit(:password))[:password]
    end

    def log_in(user)
      session[:user_id] = user.id
    end

    def log_out
      session.delete(:user_id)
      @current_user = nil
    end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  def new
    if !logged_in?
      redirect_to login_path
    end
    @topic = Topic.new
  end

  def index
    @topics = Topic.all.includes(:favorite_users)
  end

  def create
    @topic = current_user.topics.new(topic_params)

    if @topic.save
      redirect_to topics_path, success: '投稿に成功しました'
    else
      flash.now[:danger] = "投稿に失敗しました"
      render :new
    end
  end

  private
  def topic_params
    params.require(:topic).permit(:image, :description)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to root_path, success: '登録が完了しました'
    else
      flash.now[:danger] = "登録に失敗しました"
      render :new
    end
  end

  private
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/favrites_helper.rb
module FavritesHelper
end

app/helpers/p_comments_helper.rb
module PCommentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/new.html.erb
<div class="topic-new-wrapper" >
  <div class="container">
    <div class="row">
      <div class="col-md-6 col-md-offset-3">
        <h1 class="text-center">Add Comment</h1>
        <%= form_for @comment do |f| %>

          <div class="form-group">
            <%= f.label :lines %>
            <%= f.text_area :lines, class: 'form-control' %>
          </div>
          <input type="hidden" name="topic_id" id="topic_id" value="<%= @topic_id.to_s =%>" />
          <%= f.submit '投稿', class: 'btn btn-black btn-block' %>

        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/favorites/index.html.erb
<div class="topic-index-wrapper">
  <div class="container">
    <% @favorite_topics.each do |topic| %>
      <div class="row">
        <div class="col-md-6 col-md-offset-3">
          <div class="topic-index-single">
            <h2 class="topic-author">
              <%= topic.user.name %>
            </h2>
            <%= image_tag topic.image.url %>
            <%= image_tag '/images/icons/comment.png', class: 'topic-index-icon', alt: 'コメント' %>
            <p class="topic-text">
              <%= topic.description %>
            </p>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/topics/index.html.erb
<div class="topic-index-wrapper">
  <div class="container">
    <% @topics.each do |topic| %>
      <div class="row">
        <div class="col-md-6 col-md-offset-3">
          <div class="topic-index-single">
            <h2 class="topic-author">
              <%= topic.user.name %>
            </h2>
            <%= image_tag topic.image.url %>
            <ul class = "topic_idx_bar">
              <% if topic.favorite_users.include?(current_user) %>
                  <%= link_to favorites_path(topic_id: topic.id), method: :delete do %>
                   <%= image_tag '/images/icons/topic_heart_red.png', class: 'topic-index-icon', alt: "ハート" %>
                   <%#= image_tag '/images/icons/topic_heart_red.png', alt: "ハート" %>
                  <% end %>
              <% else %>
                  <% if !topic.favorite_users.include?(current_user) %>
                    <%= link_to favorites_path(topic_id: topic.id), method: :post do %>
                      <%= image_tag '/images/icons/topic_heart_black.png', class: 'topic-index-icon', alt: "黒ハート" %>
                      <%#= image_tag '/images/icons/topic_heart_black.png', alt: "黒ハート" %>
                    <% end %>
                  <% end %>
              <% end %>
                <%= sprintf("%-7d", topic.favorite_users.count).gsub(/ /, '&nbsp;').html_safe %>
                <%= link_to comments_path + '?topic_id=' + topic.id.to_s do %>
                   <%= image_tag '/images/icons/comment.png', class: 'topic-index-icon', alt: "投稿" %>
                <% end %>
            </ul>
            <h3>Comments</h3>
            <p class="topic-text">
              <%= topic.user.name + '：' + topic.description %>
            </p>
            <ul>
              <% topic.comments.each do |comment| %>
              <li>
                <%= comment.lines %>
              </li>
              <% end %>
            </ul>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/topics/new.html.erb
<div class="topic-new-wrapper" >
  <div class="container">
    <div class="row">
      <div class="col-md-6 col-md-offset-3">
        <h1 class="text-center">Add Picture</h1>
        <%= form_for @topic do |f| %>
          <div class="form-group">
            <%= f.label :image %>
            <%= f.file_field :image%>
          </div>

          <div class="form-group">
            <%= f.label :description %>
            <%= f.text_area :description, class: 'form-control' %>
          </div>

          <% if logged_in? %>
            <%= f.submit '投稿', class: 'btn btn-black btn-block' %>
          <% end %>

        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/topics/show.html.erb
<div class="topic-index-wrapper">
  <div class="container">
    <% @topics.each do |@topic| %>
      <div class="row">
        <div class="col-md-6 col-md-offset-3">
          <div class="topic-index-single">
            <h2 class="topic-author">
              <%= topic.user.name %>
            </h2>
            <%= image_tag @topic.image.url %>
            <ul class = "topic_idx_bar">
              <% if topic.comment_users.include?(current_user) %>
                <li>
                  <%= link_to comments_path(topic_id: @topic.id), method: :delete do %>
                   <%= image_tag '/images/icons/topic_comment.png', class: 'topic-index-icon', alt: "コメント" %>
                   <%#= image_tag '/images/icons/topic_comment.png', alt: "コメント" %>
                  <% end %>
                </li>
              <% else %>
                <li>
                  <% if !topic.comment_users.include?(current_user) %>
                    <%= link_to comments_path(topic_id: @topic.id), method: :post do %>
                     <%= image_tag '/images/icons/topic_comment.png', class: 'topic-index-icon', alt: "コメント" %>
                      <%#= image_tag '/images/icons/topic_comment.png', alt: "コメント" %>
                    <% end %>
                  <% end %>
                </li>
              <% end %>
              <li>
                <%= sprintf("%-7d", topic.comment_users.count).gsub(/ /, '&nbsp;').html_safe %>
              </li>
              <li>
                <%= link_to comments_path + '?topic_id=' + topic.id.to_s do %>
                   <%= image_tag '/images/icons/comment.png', class: 'topic-index-icon', alt: "投稿" %>
                <% end %>
              </li>
            </ul>
            <p class="topic-text">
              <%= topic.user.name + '：' + topic.description %>
            </p>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/users/new.html.erb
<div class="users-new-wrapper">
  <div class="container">
    <div class="row">
      <div class="col-md-offset-4 col-md-4 users-new-container">
        <h1 lass="text-center text-white">Sign up</h1>
        <%= form_for @user do |f| %>
          <div class="form-group">
            <%= f.label :name, class: 'text-white' %>
            <%= f.text_field :name, class: 'form-control' %>
          </div>
          <div class="form-group">
            <%= f.label :email, class: 'text-white' %>
            <%=f.text_field :email, class: 'form-control' %>
          </div>
          <div class="form-group">
            <%= f.label :password, class: 'text-white' %>
            <%= f.password_field :password, class: 'form-control' %>
          </div>
          <div class="form-group">
            <%= f.label :password_confirmation, class: 'text-white' %>
            <%= f.password_field :password_confirmation, class: 'form-control' %>
          </div>

          <%= f.submit "登録", class: 'btn-block btn-white' %>
        <% end %>
        <%= link_to 'ログインはこちら', 'login_path',class: 'text-white' %>
      </div>
    </div>
  </div>
</div>